#ifndef _CHASSIS_MOTOR_DATA_
#define _CHASSIS_MOTOR_DATA_

#define CHASSIS_MOTOR_YAW_SPEED_PID_KP          200.0f
#define CHASSIS_MOTOR_YAW_SPEED_PID_KI          10.0f
#define CHASSIS_MOTOR_YAW_SPEED_PID_KD          0.0f
#define CHASSIS_MOTOR_YAW_SPEED_PID_MAX_OUT     30000.0f
#define CHASSIS_MOTOR_YAW_SPEED_PID_MAX_IOUT    10000.0f 

#define CHASSIS_MOTOR_YAW_ANGLE_PID_KP          70.0f
#define CHASSIS_MOTOR_YAW_ANGLE_PID_KI          0.0f
#define CHASSIS_MOTOR_YAW_ANGLE_PID_KD          0.0f
#define CHASSIS_MOTOR_YAW_ANGLE_PID_MAX_OUT     30000.0f
#define CHASSIS_MOTOR_YAW_ANGLE_PID_MAX_IOUT    10000.0f 

#define CHASSIS_MOTOR_PITCH_SPEED_PID_KP          8.0f
#define CHASSIS_MOTOR_PITCH_SPEED_PID_KI          1.0f
#define CHASSIS_MOTOR_PITCH_SPEED_PID_KD          0.0f
#define CHASSIS_MOTOR_PITCH_SPEED_PID_MAX_OUT     16000.0f
#define CHASSIS_MOTOR_PITCH_SPEED_PID_MAX_IOUT    2000.0f 

#define CHASSIS_MOTOR_PITCH_ANGLE_PID_KP          300.0f
#define CHASSIS_MOTOR_PITCH_ANGLE_PID_KI          0.0f
#define CHASSIS_MOTOR_PITCH_ANGLE_PID_KD          0.0f
#define CHASSIS_MOTOR_PITCH_ANGLE_PID_MAX_OUT     9000.0f
#define CHASSIS_MOTOR_PITCH_ANGLE_PID_MAX_IOUT    2000.0f 

#endif 
